### ISSUE TITLE
Magento fail: laminas contain identical file names

### ISSUE THREAD

**Issue by jtsSTECH** [zepgram/magento2-fast-vm#100]
zepgram:     The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    zepgram:     Unzip with unzip command failed, falling back to ZipArchive class
    zepgram:     Install of laminas/laminas-dependency-plugin failed
    zepgram:
    zepgram: In ZipDownloader.php line 212:
    zepgram:
    zepgram:   The archive may contain identical file names with different capitalization
    zepgram:   (which fails on case insensitive filesystems): ZipArchive::extractTo(/home/
    zepgram:   vagrant/magento/vendor/composer/d2b24ea8/laminas-laminas-dependency-plugin-
    zepgram:   73cfb63/.laminas-ci.json): Operation failed: Operation not permitted
    zepgram:
    zepgram:
    zepgram: In ZipDownloader.php line 199:
    zepgram:
    zepgram:   ZipArchive::extractTo(/home/vagrant/magento/vendor/composer/d2b24ea8/lamina
    zepgram:   s-laminas-dependency-plugin-73cfb63/.laminas-ci.json): Operation failed: Op
    zepgram:   eration not permitted

**Comment by jtsSTECH** [comment]
Actual error is that the plugin fails to extract.
 zepgram:   - Locking symfony/yaml (v5.0.11)
    zepgram:   - Locking tedivm/jshrink (v1.4.0)
    zepgram:   - Locking temando/module-shipping (2.0.0)
    zepgram:   - Locking temando/module-shipping-remover (1.0.0)
    zepgram:   - Locking thecodingmachine/safe (v1.3.3)
    zepgram:   - Locking theseer/tokenizer (1.2.1)
    zepgram:   - Locking tubalmartin/cssmin (v4.1.1)
    zepgram:   - Locking web-token/jwt-framework (v2.2.11)
    zepgram:   - Locking webimpress/safe-writer (2.2.0)
    zepgram:   - Locking webmozart/assert (1.10.0)
    zepgram:   - Locking webonyx/graphql-php (v14.11.6)
    zepgram:   - Locking weew/helpers-array (v1.3.1)
    zepgram:   - Locking wikimedia/less.php (v3.1.0)
    zepgram: Writing lock file
    zepgram: Installing dependencies from lock file (including require-dev)
    zepgram: Package operations: 549 installs, 0 updates, 0 removals
    zepgram:   - Downloading laminas/laminas-dependency-plugin (2.2.0)
    zepgram:   - Installing laminas/laminas-dependency-plugin (2.2.0): Extracting archive
    zepgram:     Failed to extract laminas/laminas-dependency-plugin: (1) '/usr/bin/unzip' -qq '/home/vagrant/magento/vendor/composer/tmp-7a7ea36b19de52481fbf219dfeeb6f47' -d '/home/vagrant/magento/vendor/composer/d2b24ea8'

**Comment by zepgram** [comment]
There is a known issue with Windows that I could not resolve: https://github.com/zepgram/magento2-fast-vm/issues/70. 
The only workaround I found is to run the installation with "rsync" mount option, then after the installation you should be able to switch to "nfs".

This issue is pretty bad, because it appears only on few Windows computer, I never found the common point, and I never been able to reproduce it my self.

**Comment by jtsSTECH** [comment]
Rock on!  Retried it with Rsync and worked flawlessly.  Can you update your instructions for Windows folks?  Your system is the best one on the planet and so easy to use!  Thanks for your work!
