### ISSUE TITLE
magento2-fast-vm does not work

### ISSUE THREAD

**Issue by srgrbkl** [zepgram/magento2-fast-vm#101]
I tried to deploy magento2-fast-vm but it doesn't work, i get a lot of errors like this for example:
```
 magento2: W: The repository 'https://packages.sury.org/php stretch Release' does not have a Release file.
 magento2: E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages  403  Forbidden
...........................................................................................................................................
magento2: /tmp/vagrant-shell: line 86: php: command not found
...........................................................................................................................................
magento2: /tmp/vagrant-shell: line 123: /etc/init.d/php8.1-fpm: No such file or directory
.... etc
```

maybe problem is that debian 9 end of life was reached on June 30th, 2022
https://9to5linux.com/debian-gnu-linux-9-stretch-lts-support-reached-end-of-life-upgrade-now
i tested this box https://app.vagrantup.com/geerlingguy/boxes/debian11 and it works good but need to fix shell commands
![Screenshot_13](https://user-images.githubusercontent.com/17824457/177299134-64e7d746-9a38-463f-9593-902d95ad2e80.png)

![Screenshot_14](https://user-images.githubusercontent.com/17824457/177299143-2973bede-30dd-4fc4-912a-cec0de46f2c5.png)
 also need to fix nodejs package
![Screenshot_15](https://user-images.githubusercontent.com/17824457/177328757-ea52bb72-cb2c-4a47-9a47-e025302bd0c5.png)

**Comment by zepgram** [comment]
Hello, thanks for your reporting.

Yep you're right, during last adaptation for compatibility with Magento 2.4.4, I wanted to update the machine but I didn't had the time to do it.
I'll upgrade to bullseye asap.

**Comment by zepgram** [comment]
Hi, this should work now with version 1.6.0

I got some an issue with NFS on linux ubuntu 20.04, it seems related to vagrant or something... I couldn't find a way to solve it properly.

**Comment by srgrbkl** [comment]
Hello @zepgram, i tested new 1.6.0 version and have errors:

1. grunt not work ( i think becase npm not installed correct), see my first comment above https://user-images.githubusercontent.com/17824457/177328757-ea52bb72-cb2c-4a47-9a47-e025302bd0c5.png
2.phpinfo not work (i think php server version is wrong 
![Screenshot_8](https://user-images.githubusercontent.com/17824457/178352228-4f23f0f0-effc-4e47-acaf-3efce6036bb0.png)
)
3.adminer not work(i think php server version is wrong )
4. mailcatcher not work(i think problem here
![Screenshot_7](https://user-images.githubusercontent.com/17824457/178352016-2cc901e2-ba97-444c-abab-dcd5c47bb9f6.png)
)

**Comment by zepgram** [comment]
Yep thanks for that.
Looks like there is a lot of issue to resolve before upgrading to debian bullseye (for mailcatcher and grunt atleast).

So I just tried the version below: debian 10 buster and everything looks right.
For nginx I just solved the issue, the php-fpm absolute path had changed between the 2 versions.

Tell me if it's fine for you

**Comment by srgrbkl** [comment]
@zepgram good work, now its work fine

**Comment by srgrbkl** [comment]
@zepgram old versions m2 (for example 2.4.2 or 2.3.7) not  work

**Comment by zepgram** [comment]
Thanks for reporting @srgrbkl

This is related to percona installation which is different on buster machine for deb selection.

I found out more info here: https://stackoverflow.com/questions/36667254/unattended-percona-server-5-7-install-on-debian-jessie

Preparing a fix soon.

**Comment by zepgram** [comment]
![ACP_logo](https://user-images.githubusercontent.com/16258478/182574034-662e3aeb-318a-496d-9b65-9a927e8782e0.png)
