### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by srgrbkl** [zepgram/magento2-fast-vm#105]
magento2test: Setting up grub2-common (2.06-3~deb10u1) ...
    magento2test: Installing new version of config file /etc/kernel/postinst.d/zz-update-grub ...
    magento2test: Installing new version of config file /etc/kernel/postrm.d/zz-update-grub ...
    magento2test: Setting up libcurl3-gnutls:amd64 (7.64.0-4+deb10u3) ...
    magento2test: Setting up grub-pc-bin (2.06-3~deb10u1) ...
    magento2test: Setting up grub-pc (2.06-3~deb10u1) ...
    magento2test: /dev/disk/by-id/ata-VBOX_HARDDISK_VB037eca03-3a829d7e does not exist, so cannot grub-install to it!
    magento2test: You must correct your GRUB install devices before proceeding:
    magento2test: 
    magento2test:   DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
    magento2test:   dpkg --configure -a
    magento2test: dpkg: error processing package grub-pc (--configure):
    magento2test:  installed grub-pc package post-installation script subprocess returned error exit status 1
    magento2test: Setting up libisccfg163:amd64 (1:9.11.5.P4+dfsg-5.1+deb10u7) ...
    magento2test: Setting up libbind9-161:amd64 (1:9.11.5.P4+dfsg-5.1+deb10u7) ...
    magento2test: Setting up bind9-host (1:9.11.5.P4+dfsg-5.1+deb10u7) ...
    magento2test: Processing triggers for systemd (241-7~deb10u8) ...
    magento2test: Processing triggers for man-db (2.8.5-2) ...
    magento2test: Processing triggers for libc-bin (2.28-10+deb10u1) ...
    magento2test: Errors were encountered while processing:
    magento2test:  grub-pc
    magento2test: E: Sub-process /usr/bin/dpkg returned an error code (1)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by zepgram** [comment]
Hello,

You can try to execute `apt install grub-pc` and `dpkg-reconfigure grub-pc`

Also, the VirtualBox hard disk could not be found, so there is maybe an issue with the VM

**Comment by curkle** [comment]
got same error

**Comment by zepgram** [comment]
The problem is due to kernel version, an upgrade is required and when it does, it breaks because it is an interactive upgrade, which is not available on non-interractive.

Working on it, I'll tell you when it will be solved

**Comment by zepgram** [comment]
Solved with merge request [#106]

Thanks for reporting the issue, have a nice day 🌞

**Comment by srgrbkl** [comment]
now its working, thanks @zepgram!!!
