### ISSUE TITLE
deployment not completed

### ISSUE THREAD

**Issue by srgrbkl** [zepgram/magento2-fast-vm#13]
after  first run  vagrant I get an error  "/srv/magento/bin/magento command not found vagrant", I looked at deployment files and really did not find  "bin" directory (Windows10, VirtualBox 5.2.22, Vagrant 2.2.2)
![screenshot_2](https://user-images.githubusercontent.com/17824457/50426074-e52f3d00-088d-11e9-8917-6dc3d9133111.png)

**Comment by zepgram** [comment]
Hi, composer installation failed.
This issue is very recent and problem is on Magento side.
An issue has been opened on official repository and is related here: github.com/magento/magento2/issues/19934

**Comment by srgrbkl** [comment]
@zepgram thanks, adding to composer.json "replace": {"vertex/module-tax": "*",} solved problem
