### ISSUE TITLE
Loading existing project

### ISSUE THREAD

**Issue by ramzdam** [zepgram/magento2-fast-vm#15]
Hi I was able to install this box. But it seems that the files that I copied didn't take effect and eventhough I changed the DB to use our existing DB it's still throwing an error.

I have this error when refreshing the page

1 exception(s):
Exception #0 (Exception): Notice: Undefined index:  in /srv/magento/vendor/magento/module-developer/Model/View/Page/Config/RendererFactory.php on line 70

Exception #0 (Exception): Notice: Undefined index:  in /srv/magento/vendor/magento/module-developer/Model/View/Page/Config/RendererFactory.php on line 70

**Comment by zepgram** [comment]
Hi Ramzdam,

Could you tell me which version of Magento you are trying to install ?
This issue has been related on Magento stack exchange and official repository for Magento 2.1:
https://magento.stackexchange.com/questions/192057/magento-2-notice-undefined-index-rendererfactory-php-on-line-64
https://github.com/magento/magento2/issues/8619

**Comment by ramzdam** [comment]
@zepgram yeah found the solution by clearing everything deleting the pub/static, generated and did the bin/magento setup:upgrade, bin/magento setup:di:compile and static-deploy. But one of the issue I encountered is upon solving this issue I get the error of  [sodiumchachaietfdecrypt error](https://magento.stackexchange.com/questions/260080/sodiumchachaietfdecrypt-must-be-of-the-type-string-boolean). I had the modify the vendor/magento/framework which I think is not the correct approach. My specs are

Magento Version: 2.3.1

**Comment by zepgram** [comment]
Yep I think it's related to your dump, the crypt key in app/etc/config.php cannot decrypt data in your core_config_data table.
Try to put your encrypted key in app/etc/config.php from your production environment and this should work.

**Comment by zepgram** [comment]
My bad it's app/etc/env.php
```
  'crypt' =>
  array (
    'key' => 'xxxx',
  ),
```

**Comment by ramzdam** [comment]
That make sense. Although on our repository the key is already set. But I'm not sure if the value of the staging is the same. Will be commenting back if this resolves the issue. Thanks for the prompt reply

**Comment by zepgram** [comment]
Hi Ramzdam,

Does this solve the issue ?

**Comment by ramzdam** [comment]
> Hi Ramzdam,
> 
> Does this solve the issue ?

Yes actually I just did a new bin/magento setup:di:compile and setup:static-content-deploy. It somehow regenerated the encryption or something. I tried the solution you gave me but didn't work. But overall it's all good now since recompiling the assets and data fixed it
