### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by DeanMorganMB** [zepgram/magento2-fast-vm#22]
I have tried twice to boot this VM but both times I run into the same problem.

PHP Fatal error:  Uncaught Error: Class 'Composer\Autoload\ComposerStaticInit6fd50736163f37222d3a28779c21eaf9' not found in /srv/magento/vendor/composer/autoload_real.php:34

I've attached my console log (well as far back as it would go) in case there is anything in that which could help. 

[console-error-during-vagrant-up.txt](https://github.com/zepgram/magento2-fast-vm/files/3252690/console-error-during-vagrant-up.txt)

I've followed all the steps in the readme.md and as far as I can tell, have done everything correctly.

**Comment by zepgram** [comment]
Hi,

Could you share me values: mount, path, url, source, edition, version, php_version from your config.yaml ?

**Comment by zepgram** [comment]
I just tried with those config:
  source: 'composer'
  edition: 'community'
  version: '2.3.1'
  php_version: 'default'
  sample: 'false'

And it was fine:
<img width="694" alt="autoload" src="https://user-images.githubusercontent.com/16258478/58887092-441e9b00-86e5-11e9-9148-37c914b97019.PNG">

I'll give an other try, it might be link to sample data.

**Comment by DeanMorganMB** [comment]
vmconf:
  machine_name: 'Vagrant Magento 2'
  network_ip: '192.168.200.50'
  host_name: 'zepgram'
  memory: '4096'
  cpus: '2'
  mount: 'nfs'
  path: 'root'
  provision: 'all'
composer:
  username: '------------removed------------'
  password: '------------removed------------'
magento:
  url: 'dev.magento.com'
  source: 'composer'
  edition: 'community'
  version: '2.3.1'
  php_version: 'default'
  sample: 'true'
  mode: 'developer'
  currency: 'GBP'
  language: 'en_GB'
  time_zone: 'Europe/London'

**Comment by DeanMorganMB** [comment]
Just tried this again but with sample data disabled and everything appears to have worked correctly.

**Comment by zepgram** [comment]
Nice.
On my side I could not reproduce, everything worked. Did you retry with sample ?
If it doesn't work you can add them after the installation by using ``bin/magento sampledata:deploy``

**Comment by DeanMorganMB** [comment]
I can confirm that everything is now working as it should be. I've made zero changes at this end compared to when it was failing, so perhaps it was a temporary issue with one of the modules/third party bits used during the setup.

Either way, all is working and this can be considered closed I believe.
