### ISSUE TITLE
Timezone of Debian VM

### ISSUE THREAD

**Issue by narjamp** [zepgram/magento2-fast-vm#24]
First : One BIG Thanks for your solution, it is really fast, specially comparing with one I used before.
I have problems with system time of Debian VM. In parameter file "config.yamI" I enter for time zone: time_zone: 'Europe/Vienna'. All VM set-up goes well only system (Debian) time zone is not equal to Magento (this is correct regarding set-up parameters)
$ timedatectl
      Local time: Tue 2019-06-18 21:16:25 GMT
     Universal time: Tue 2019-06-18 21:16:25 UTC
     RTC time: Tue 2019-06-18 21:16:23
     Time zone: Etc/GMT+0 (GMT, +0000)
     Network time on: yes
     NTP synchronized: no
     RTC in local TZ: no  
System time is 2 hours less than Magento time, I think I have some other problems in Magento development caused by this fact.
My question: is my timezone situation normal ? How to setup Debian VM with same time zone as is in jaml parameter file (and as is in Magento).

Info about my system:
mac OS Mojove
VirtualBox 5.2.28
Vagrant 2.2.4
Magento 2.3.1 Community + sample data 

Thanks in advance for your effort and time to help us, me
Marjan Pečar, Slovenia

**Comment by zepgram** [comment]
Hi Narjamp,

The VM is based on UTC and Magento on GTM local timezone inherited from config.yaml.
This is the normal behaviour.

But if you want to change the VM local timezone you can use this:
```sudo dpkg-reconfigure tzdata```

I hope it's helpful.
