### ISSUE TITLE
Error on Vagrant Up

### ISSUE THREAD

**Issue by DeanMorganMB** [zepgram/magento2-fast-vm#26]
Everything had been working fine for me until yesterday's updates and now it fails whenever I run the vagrant up command.

Here are the contents from my config.yaml file

vmconf:
  machine_name: 'Vagrant Magento 2'
  network_ip: '192.168.200.50'
  host_name: 'zepgram'
  memory: '4096'
  cpus: '1'
  mount: 'nfs'
  path: 'root'
  provision: 'all'
composer:
  username: '----removed----'
  password: '----removed----'
git:
  name: 'DeanMorganMB'
  email: 'deanmorgan@mediablox.co.uk'
  host: 'github.com'
  repository: 'ssh://git@github.com:project-name.git'
magento:
  url: 'dev.magento.com'
  source: 'composer'
  edition: 'community'
  version: '2.3.1'
  php_version: 'default'
  sample: 'true'
  mode: 'developer'
  currency: 'GBP'
  language: 'en_GB'
  time_zone: 'Europe/London'

Any help would be appreciated.

[error-log.txt](https://github.com/zepgram/magento2-fast-vm/files/3314195/error-log.txt)

**Comment by zepgram** [comment]
Hi, thanks for logs and config.yaml.

Everything is working correctly on my side, looks like a random error :/
Could you retry after vagrant destroy and remove the 'www' directory ?

**Comment by DeanMorganMB** [comment]
It seems to be very hit and miss for me, I'm really not sure why either.

I have had this work for me today, and then within an hour or so it isn't working again.

I made no changes to the config.yaml in between the vagrant up's.

I'm going to try this once more now, and see if it works. If this

**Comment by DeanMorganMB** [comment]
Just to keep things up-to-date with my progress...

Just ran again and everything is working as expected.

I don't think that any of the issues I have been having are a direct result of this project, so I'd have to mark this issue as closed.
