### ISSUE TITLE
magento-composer-installer does not exist and could not be created (source: 'branch')

### ISSUE THREAD

**Issue by srgrbkl** [zepgram/magento2-fast-vm#29]
![Screenshot_7](https://user-images.githubusercontent.com/17824457/62139220-9f3dca00-b2f1-11e9-90e2-cf56a9d80246.png)

**Comment by zepgram** [comment]
Hi,

Did you retry ? sometimes composer install fails randomly.

**Comment by srgrbkl** [comment]
> Hi,
> 
> Did you retry ? sometimes composer install fails randomly.

yes, several times, did not help

**Comment by zepgram** [comment]
Ok, I need to know on which OS you are. Could you also share your config.yaml ?

**Comment by srgrbkl** [comment]
> Ok, I need to know on which OS you are. Could you also share your config.yaml ?

windows 10 64 bit

vmconf:
  machine_name: 'project'
  network_ip: '192.168.200.30'
  host_name: 'project'
  memory: '2048'
  cpus: '2'
  mount: 'rsync'
  path: 'root'
  provision: 'all'
composer:
  username: 'test'
  password: 'test'
git:
  name: 'name'
  email: 'email'
  host: 'github.com/name'
  repository: 'https://name:password@bitbucket.org/project.git'
magento:
  url: 'dev.project.com'
  source: 'git-branch-name'
  edition: 'community'
  version: '2.3.2'
  php_version: 'default'
  sample: 'false'
  mode: 'developer'
  currency: 'EUR'
  language: 'en_US'
  time_zone: 'Europe/Amsterdam'

**Comment by zepgram** [comment]
According to your config.yaml and the error in your first message, your composer 'username' and 'password' are not correct. You must create them to install Magento properly: https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

**Comment by srgrbkl** [comment]
> According to your config.yaml and the error in your first message, your composer 'username' and 'password' are not correct. You must create them to install Magento properly: https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

they are already created, I replaced from with "test" in example

**Comment by zepgram** [comment]
Ok did you try with NFS mount ? It's maybe a permission issue, and it should not happen with NFS.

**Comment by srgrbkl** [comment]
added this
![Screenshot_4](https://user-images.githubusercontent.com/17824457/63720452-e7e89480-c857-11e9-9041-834df86e7303.png)
