### ISSUE TITLE
cannot update packages

### ISSUE THREAD

**Issue by kennylawrence** [zepgram/magento2-fast-vm#33]
Hi - it seems that perhaps an apt-get update is needed somewhere..? The following is the output from bringing up the VM:

c:\Users\Kenny\Documents\GitHub\magento2-fast-vm>vagrant up
Checking dependencies...
 - All dependencies are satisfied
Checking dependencies...
 - All dependencies are satisfied
Bringing machine 'dev.magento.com' up with 'virtualbox' provider...
==> dev.magento.com: Importing base box 'debian/stretch64'...
==> dev.magento.com: Matching MAC address for NAT networking...
==> dev.magento.com: Checking if box 'debian/stretch64' version '9.9.1' is up to date...
==> dev.magento.com: Setting the name of the VM: Vagrant Magento 2
==> dev.magento.com: Clearing any previously set network interfaces...
==> dev.magento.com: Preparing network interfaces based on configuration...
    dev.magento.com: Adapter 1: nat
    dev.magento.com: Adapter 2: hostonly
    dev.magento.com: Adapter 3: hostonly
==> dev.magento.com: Forwarding ports...
    dev.magento.com: 22 (guest) => 2222 (host) (adapter 1)
==> dev.magento.com: Running 'pre-boot' VM customizations...
==> dev.magento.com: Booting VM...
==> dev.magento.com: Waiting for machine to boot. This may take a few minutes...
    dev.magento.com: SSH address: 127.0.0.1:2222
    dev.magento.com: SSH username: vagrant
    dev.magento.com: SSH auth method: private key
    dev.magento.com:
    dev.magento.com: Vagrant insecure key detected. Vagrant will automatically replace
    dev.magento.com: this with a newly generated keypair for better security.
    dev.magento.com:
    dev.magento.com: Inserting generated public key within guest...
    dev.magento.com: Removing insecure key from the guest if it's present...
    dev.magento.com: Key inserted! Disconnecting and reconnecting using new SSH key...
==> dev.magento.com: Machine booted and ready!
[dev.magento.com] No Virtualbox Guest Additions installation found.
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binutils cpp cpp-6 fakeroot gcc gcc-6 libasan3 libatomic1 libc-dev-bin
  libc6-dev libcc1-0 libcilkrts5 libfakeroot libgcc-6-dev libgomp1 libisl15
  libitm1 liblsan0 libmpc3 libmpfr4 libmpx2 libquadmath0 libtsan0 libubsan0
  linux-compiler-gcc-6-x86 linux-headers-4.9.0-9-common linux-headers-amd64
  linux-kbuild-4.9 linux-libc-dev make manpages-dev patch
Suggested packages:
  binutils-doc cpp-doc gcc-6-locales python3-apport menu gcc-multilib autoconf
  automake libtool flex bison gdb gcc-doc gcc-6-multilib gcc-6-doc libgcc1-dbg
  libgomp1-dbg libitm1-dbg libatomic1-dbg libasan3-dbg liblsan0-dbg
  libtsan0-dbg libubsan0-dbg libcilkrts5-dbg libmpx2-dbg libquadmath0-dbg
  glibc-doc make-doc ed diffutils-doc
The following NEW packages will be installed:
  binutils cpp cpp-6 dkms fakeroot gcc gcc-6 libasan3 libatomic1 libc-dev-bin
  libc6-dev libcc1-0 libcilkrts5 libfakeroot libgcc-6-dev libgomp1 libisl15
  libitm1 liblsan0 libmpc3 libmpfr4 libmpx2 libquadmath0 libtsan0 libubsan0
  linux-compiler-gcc-6-x86 linux-headers-4.9.0-9-amd64
  linux-headers-4.9.0-9-common linux-headers-amd64 linux-kbuild-4.9
  linux-libc-dev make manpages-dev patch
0 upgraded, 34 newly installed, 0 to remove and 0 not upgraded.
Need to get 38.3 MB of archives.
After this operation, 172 MB of additional disk space will be used.
Err:1 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 linux-libc-dev amd64 4.9.168-1+deb9u2
  404  Not Found
Get:6 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 binutils amd64 2.28-5 [3,770 kB]
Err:2 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 linux-compiler-gcc-6-x86 amd64 4.9.168-1+deb9u2
  404  Not Found
Get:7 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libisl15 amd64 0.18-1 [564 kB]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libmpfr4 amd64 3.1.5-1 [556 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libmpc3 amd64 1.0.3-1+b2 [39.9 kB]
Get:10 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 cpp-6 amd64 6.3.0-18+deb9u1 [6,584 kB]
Err:3 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 linux-headers-4.9.0-9-common all 4.9.168-1+deb9u2
  404  Not Found
Get:11 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 cpp amd64 4:6.3.0-4 [18.7 kB]
Get:12 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libcc1-0 amd64 6.3.0-18+deb9u1 [30.6 kB]
Get:13 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libgomp1 amd64 6.3.0-18+deb9u1 [73.3 kB]
Get:14 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libitm1 amd64 6.3.0-18+deb9u1 [27.3 kB]
Get:15 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libatomic1 amd64 6.3.0-18+deb9u1 [8,966 B]
Get:16 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libasan3 amd64 6.3.0-18+deb9u1 [311 kB]
Get:17 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 liblsan0 amd64 6.3.0-18+deb9u1 [115 kB]
Get:18 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libtsan0 amd64 6.3.0-18+deb9u1 [257 kB]
Get:19 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libubsan0 amd64 6.3.0-18+deb9u1 [107 kB]
Get:20 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libcilkrts5 amd64 6.3.0-18+deb9u1 [40.5 kB]
Get:21 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libmpx2 amd64 6.3.0-18+deb9u1 [11.2 kB]
Get:22 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libquadmath0 amd64 6.3.0-18+deb9u1 [131 kB]
Get:23 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libgcc-6-dev amd64 6.3.0-18+deb9u1 [2,296 kB]
Err:4 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 linux-kbuild-4.9 amd64 4.9.168-1+deb9u2
  404  Not Found
Get:24 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 gcc-6 amd64 6.3.0-18+deb9u1 [6,900 kB]
Err:5 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 linux-headers-4.9.0-9-amd64 amd64 4.9.168-1+deb9u2
  404  Not Found
Get:25 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 gcc amd64 4:6.3.0-4 [5,196 B]
Get:26 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 make amd64 4.1-9.1 [302 kB]
Err:27 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 patch amd64 2.7.5-1+deb9u1
  404  Not Found
Get:28 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 dkms all 2.3-2 [74.8 kB]
Get:29 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libfakeroot amd64 1.21-3.1 [45.7 kB]
Get:30 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 fakeroot amd64 1.21-3.1 [85.6 kB]
Get:31 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libc-dev-bin amd64 2.24-11+deb9u4 [259 kB]
Get:32 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libc6-dev amd64 2.24-11+deb9u4 [2,364 kB]
Get:33 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 linux-headers-amd64 amd64 4.9+80+deb9u7 [6,040 B]
Get:34 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 manpages-dev all 4.10-2 [2,145 kB]
Fetched 27.1 MB in 2s (13.2 MB/s)
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/p/patch/patch_2.7.5-1+deb9u1_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/debian-security/pool/updates/main/l/linux/linux-libc-dev_4.9.168-1+deb9u2_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/debian-security/pool/updates/main/l/linux/linux-compiler-gcc-6-x86_4.9.168-1+deb9u2_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-4.9.0-9-common_4.9.168-1+deb9u2_all.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/debian-security/pool/updates/main/l/linux/linux-kbuild-4.9_4.9.168-1+deb9u2_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-4.9.0-9-amd64_4.9.168-1+deb9u2_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Get:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:2 http://security-cdn.debian.org/debian-security stretch/updates/main Sources [189 kB]
Get:4 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages [497 kB]
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2,365 B]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch/main Sources [6,747 kB]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7,086 kB]
Fetched 14.7 MB in 2s (4,985 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-headers-4.9.0-9-amd64
E: Couldn't find any package by glob 'linux-headers-4.9.0-9-amd64'
E: Couldn't find any package by regex 'linux-headers-4.9.0-9-amd64'
==> dev.magento.com: Checking for guest additions in VM...
    dev.magento.com: No guest additions were detected on the base box for this VM! Guest
    dev.magento.com: additions are required for forwarded ports, shared folders, host only
    dev.magento.com: networking, and more. If SSH fails on this machine, please install
    dev.magento.com: the guest additions and repackage the box to continue.
    dev.magento.com:
    dev.magento.com: This is not an error message; everything may continue to work properly,
    dev.magento.com: in which case you may ignore this message.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y linux-headers-`uname -r` dkms

Stdout from the command:

Reading package lists...
Building dependency tree...
Reading state information...

Stderr from the command:

E: Unable to locate package linux-headers-4.9.0-9-amd64
E: Couldn't find any package by glob 'linux-headers-4.9.0-9-amd64'
E: Couldn't find any package by regex 'linux-headers-4.9.0-9-amd64'

c:\Users\Kenny\Documents\GitHub\magento2-fast-vm>

**Comment by zepgram** [comment]
Hi your issue start on very beginning of the installation.
It looks like required Debian package have been removed :
https://packages.debian.org/stretch/linux-headers-4.9.0-9-common
I'll try on my side to confirm.

**Comment by zepgram** [comment]
I've the same issue.
At this point we must try Debian buster, stretch image is not supported anymore, maybe they'll do something about it.
If you want to try, just go on Vagrant file and replace https://github.com/zepgram/magento2-fast-vm/blob/c9c77fa4b06cdae2c25032db4131ccbe16f5ce84/Vagrantfile#L40
By "debian/buster64"

**Comment by kennylawrence** [comment]
Hi - looks like similar result:

c:\Users\Kenny\Documents\GitHub\magento2-fast-vm>vagrant up
Checking dependencies...
 - All dependencies are satisfied
Checking dependencies...
 - All dependencies are satisfied
Bringing machine 'dev.magento.com' up with 'virtualbox' provider...
==> dev.magento.com: Box 'debian/buster64' could not be found. Attempting to find and install...
    dev.magento.com: Box Provider: virtualbox
    dev.magento.com: Box Version: >= 0
==> dev.magento.com: Loading metadata for box 'debian/buster64'
    dev.magento.com: URL: https://vagrantcloud.com/debian/buster64
==> dev.magento.com: Adding box 'debian/buster64' (v10.0.0) for provider: virtualbox
    dev.magento.com: Downloading: https://vagrantcloud.com/debian/boxes/buster64/versions/10.0.0/providers/virtualbox.box
    dev.magento.com: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    dev.magento.com:
==> dev.magento.com: Successfully added box 'debian/buster64' (v10.0.0) for 'virtualbox'!
==> dev.magento.com: Importing base box 'debian/buster64'...
==> dev.magento.com: Matching MAC address for NAT networking...
==> dev.magento.com: Checking if box 'debian/buster64' version '10.0.0' is up to date...
==> dev.magento.com: Setting the name of the VM: Vagrant Magento 2
==> dev.magento.com: Clearing any previously set network interfaces...
==> dev.magento.com: Preparing network interfaces based on configuration...
    dev.magento.com: Adapter 1: nat
    dev.magento.com: Adapter 2: hostonly
    dev.magento.com: Adapter 3: hostonly
==> dev.magento.com: Forwarding ports...
    dev.magento.com: 22 (guest) => 2222 (host) (adapter 1)
==> dev.magento.com: Running 'pre-boot' VM customizations...
==> dev.magento.com: Booting VM...
==> dev.magento.com: Waiting for machine to boot. This may take a few minutes...
    dev.magento.com: SSH address: 127.0.0.1:2222
    dev.magento.com: SSH username: vagrant
    dev.magento.com: SSH auth method: private key
    dev.magento.com:
    dev.magento.com: Vagrant insecure key detected. Vagrant will automatically replace
    dev.magento.com: this with a newly generated keypair for better security.
    dev.magento.com:
    dev.magento.com: Inserting generated public key within guest...
    dev.magento.com: Removing insecure key from the guest if it's present...
    dev.magento.com: Key inserted! Disconnecting and reconnecting using new SSH key...
==> dev.magento.com: Machine booted and ready!
[dev.magento.com] GuestAdditions versions on your host (6.0.12) and guest (5.2.0) do not match.
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu build-essential cpp cpp-8
  dirmngr dpkg-dev fakeroot g++ g++-8 gcc gcc-8 gnupg gnupg-l10n gnupg-utils
  gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
  libasan5 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libdpkg-perl
  libfakeroot libfile-fcntllock-perl libgcc-8-dev libgomp1 libisl19 libitm1
  libksba8 liblsan0 libmpc3 libmpfr6 libmpx2 libnpth0 libquadmath0
  libstdc++-8-dev libtsan0 libubsan1 linux-compiler-gcc-8-x86
  linux-headers-4.19.0-5-common linux-headers-amd64 linux-kbuild-4.19
  linux-libc-dev make manpages-dev patch
Suggested packages:
  binutils-doc cpp-doc gcc-8-locales dbus-user-session pinentry-gnome3 tor
  python3-apport menu debian-keyring g++-multilib g++-8-multilib gcc-8-doc
  libstdc++6-8-dbg gcc-multilib autoconf automake libtool flex bison gdb
  gcc-doc gcc-8-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg
  libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg libmpx2-dbg
  libquadmath0-dbg parcimonie xloadimage scdaemon glibc-doc git bzr
  libstdc++-8-doc make-doc ed diffutils-doc
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu build-essential cpp cpp-8
  dirmngr dkms dpkg-dev fakeroot g++ g++-8 gcc gcc-8 gnupg gnupg-l10n
  gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
  libasan5 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libdpkg-perl
  libfakeroot libfile-fcntllock-perl libgcc-8-dev libgomp1 libisl19 libitm1
  libksba8 liblsan0 libmpc3 libmpfr6 libmpx2 libnpth0 libquadmath0
  libstdc++-8-dev libtsan0 libubsan1 linux-compiler-gcc-8-x86
  linux-headers-4.19.0-5-amd64 linux-headers-4.19.0-5-common
  linux-headers-amd64 linux-kbuild-4.19 linux-libc-dev make manpages-dev patch
0 upgraded, 58 newly installed, 0 to remove and 0 not upgraded.
Need to get 66.0 MB of archives.
After this operation, 257 MB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian buster/main amd64 binutils-common amd64 2.31.1-16 [2,073 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libbinutils amd64 2.31.1-16 [478 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster/main amd64 binutils-x86-64-linux-gnu amd64 2.31.1-16 [1,823 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 binutils amd64 2.31.1-16 [56.8 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libc-dev-bin amd64 2.28-10 [275 kB]
Err:6 http://cdn-fastly.deb.debian.org/debian buster/main amd64 linux-libc-dev amd64 4.19.37-5
  404  Not Found [IP: 151.101.180.204 80]
Get:7 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libc6-dev amd64 2.28-10 [2,691 kB]
Get:8 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libisl19 amd64 0.20-2 [587 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libmpfr6 amd64 4.0.2-1 [775 kB]
Get:10 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libmpc3 amd64 1.1.0-1 [41.3 kB]
Get:11 http://cdn-fastly.deb.debian.org/debian buster/main amd64 cpp-8 amd64 8.3.0-6 [8,914 kB]
Get:12 http://cdn-fastly.deb.debian.org/debian buster/main amd64 cpp amd64 4:8.3.0-1 [19.4 kB]
Get:13 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libcc1-0 amd64 8.3.0-6 [46.6 kB]
Get:14 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libgomp1 amd64 8.3.0-6 [75.8 kB]
Get:15 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libitm1 amd64 8.3.0-6 [27.7 kB]
Get:16 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libatomic1 amd64 8.3.0-6 [9,032 B]
Get:17 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libasan5 amd64 8.3.0-6 [362 kB]
Get:18 http://cdn-fastly.deb.debian.org/debian buster/main amd64 liblsan0 amd64 8.3.0-6 [131 kB]
Get:19 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libtsan0 amd64 8.3.0-6 [283 kB]
Get:20 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libubsan1 amd64 8.3.0-6 [120 kB]
Get:21 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libmpx2 amd64 8.3.0-6 [11.4 kB]
Get:22 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libquadmath0 amd64 8.3.0-6 [133 kB]
Get:23 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libgcc-8-dev amd64 8.3.0-6 [2,298 kB]
Get:24 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gcc-8 amd64 8.3.0-6 [9,452 kB]
Get:25 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gcc amd64 4:8.3.0-1 [5,196 B]
Get:26 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libstdc++-8-dev amd64 8.3.0-6 [1,532 kB]
Get:27 http://cdn-fastly.deb.debian.org/debian buster/main amd64 g++-8 amd64 8.3.0-6 [9,752 kB]
Get:28 http://cdn-fastly.deb.debian.org/debian buster/main amd64 g++ amd64 4:8.3.0-1 [1,644 B]
Get:29 http://cdn-fastly.deb.debian.org/debian buster/main amd64 make amd64 4.2.1-1.2 [341 kB]
Get:30 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libdpkg-perl all 1.19.7 [1,414 kB]
Err:31 http://cdn-fastly.deb.debian.org/debian buster/main amd64 patch amd64 2.7.6-3
  404  Not Found [IP: 151.101.180.204 80]
Get:32 http://cdn-fastly.deb.debian.org/debian buster/main amd64 dpkg-dev all 1.19.7 [1,773 kB]
Get:33 http://cdn-fastly.deb.debian.org/debian buster/main amd64 build-essential amd64 12.6 [7,576 B]
Get:34 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gpgconf amd64 2.2.12-1 [509 kB]
Get:35 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libksba8 amd64 1.3.5-2 [99.7 kB]
Get:36 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libnpth0 amd64 1.6-1 [18.4 kB]
Err:37 http://cdn-fastly.deb.debian.org/debian buster/main amd64 dirmngr amd64 2.2.12-1
  404  Not Found [IP: 151.101.180.204 80]
Get:38 http://cdn-fastly.deb.debian.org/debian buster/main amd64 dkms all 2.6.1-4 [74.4 kB]
Get:39 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libfakeroot amd64 1.23-1 [45.9 kB]
Get:40 http://cdn-fastly.deb.debian.org/debian buster/main amd64 fakeroot amd64 1.23-1 [85.8 kB]
Err:41 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gnupg-l10n all 2.2.12-1
  404  Not Found [IP: 151.101.180.204 80]
Get:42 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gnupg-utils amd64 2.2.12-1 [857 kB]
Get:43 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gpg amd64 2.2.12-1 [862 kB]
Get:44 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gpg-agent amd64 2.2.12-1 [617 kB]
Get:45 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gpg-wks-client amd64 2.2.12-1 [484 kB]
Err:46 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gpg-wks-server amd64 2.2.12-1
  404  Not Found [IP: 151.101.180.204 80]
Get:47 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gpgsm amd64 2.2.12-1 [602 kB]
Get:48 http://cdn-fastly.deb.debian.org/debian buster/main amd64 gnupg all 2.2.12-1 [715 kB]
Get:49 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libalgorithm-diff-perl all 1.19.03-2 [47.9 kB]
Get:50 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libalgorithm-diff-xs-perl amd64 0.04-5+b1 [11.8 kB]
Get:51 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libalgorithm-merge-perl all 0.08-3 [12.7 kB]
Get:52 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libfile-fcntllock-perl amd64 0.22-3+b5 [35.4 kB]
Err:53 http://cdn-fastly.deb.debian.org/debian buster/main amd64 linux-compiler-gcc-8-x86 amd64 4.19.37-5
  404  Not Found [IP: 151.101.180.204 80]
Err:54 http://cdn-fastly.deb.debian.org/debian buster/main amd64 linux-headers-4.19.0-5-common all 4.19.37-5
  404  Not Found [IP: 151.101.180.204 80]
Err:55 http://cdn-fastly.deb.debian.org/debian buster/main amd64 linux-kbuild-4.19 amd64 4.19.37-5
  404  Not Found [IP: 151.101.180.204 80]
Err:56 http://cdn-fastly.deb.debian.org/debian buster/main amd64 linux-headers-4.19.0-5-amd64 amd64 4.19.37-5
  404  Not Found [IP: 151.101.180.204 80]
Get:57 http://cdn-fastly.deb.debian.org/debian buster/main amd64 linux-headers-amd64 amd64 4.19+105 [6,652 B]
Get:58 http://cdn-fastly.deb.debian.org/debian buster/main amd64 manpages-dev all 4.16-2 [2,232 kB]
Fetched 52.8 MB in 8s (6,280 kB/s)
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/l/linux/linux-libc-dev_4.19.37-5_amd64.deb  404  Not Found [IP: 151.101.180.204 80]
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/p/patch/patch_2.7.6-3_amd64.deb  404  Not Found [IP: 151.101.180.204 80]
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/g/gnupg2/dirmngr_2.2.12-1_amd64.deb  404  Not Found [IP: 151.101.180.204 80]
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/g/gnupg2/gnupg-l10n_2.2.12-1_all.deb  404  Not Found [IP: 151.101.180.204 80]
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/g/gnupg2/gpg-wks-server_2.2.12-1_amd64.deb  404  Not Found [IP: 151.101.180.204 80]
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/l/linux/linux-compiler-gcc-8-x86_4.19.37-5_amd64.deb  404  Not Found [IP: 151.101.180.204 80]
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/l/linux/linux-headers-4.19.0-5-common_4.19.37-5_all.deb  404  Not Found [IP: 151.101.180.204 80]
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/l/linux/linux-kbuild-4.19_4.19.37-5_amd64.deb  404  Not Found [IP: 151.101.180.204 80]
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/l/linux/linux-headers-4.19.0-5-amd64_4.19.37-5_amd64.deb  404  Not Found [IP: 151.101.180.204 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://security-cdn.debian.org/debian-security buster/updates/main Sources [73.7 kB]
Get:4 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [93.7 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main Sources [7,832 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7,899 kB]
Fetched 16.1 MB in 3s (4,732 kB/s)
Reading package lists...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-headers-4.19.0-5-amd64
E: Couldn't find any package by glob 'linux-headers-4.19.0-5-amd64'
E: Couldn't find any package by regex 'linux-headers-4.19.0-5-amd64'
==> dev.magento.com: Checking for guest additions in VM...
    dev.magento.com: The guest additions on this VM do not match the installed version of
    dev.magento.com: VirtualBox! In most cases this is fine, but in rare cases it can
    dev.magento.com: prevent things such as shared folders from working properly. If you see
    dev.magento.com: shared folder errors, please make sure the guest additions within the
    dev.magento.com: virtual machine match the version of VirtualBox you have installed on
    dev.magento.com: your host and reload your VM.
    dev.magento.com:
    dev.magento.com: Guest Additions Version: 5.2.0 r68940
    dev.magento.com: VirtualBox Version: 6.0
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y linux-headers-`uname -r` dkms

Stdout from the command:

Reading package lists...
Building dependency tree...
Reading state information...


Stderr from the command:

E: Unable to locate package linux-headers-4.19.0-5-amd64
E: Couldn't find any package by glob 'linux-headers-4.19.0-5-amd64'
E: Couldn't find any package by regex 'linux-headers-4.19.0-5-amd64'

c:\Users\Kenny\Documents\GitHub\magento2-fast-vm>

**Comment by kennylawrence** [comment]
Is it not possible to have a apt-get update somewhere? there is a message "Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"

**Comment by zepgram** [comment]
Even if installation failed you can run vagrant SSH and try this command, but there is nothing we can do to fix it properly because it's related to VirtualBox.
My first interpretation was wrong.
The required package missing is required by guest addition (which is related to virtual box). 
So it's an issue with guest addition, and you have the latest version so they didn't fixed it.
I don't know what we can do to fix it right now.

**Comment by zepgram** [comment]
Ok, I found which is guilty ! vagrant-vbguest plugin is responsible of this error, issue has been reported on their repo:
https://github.com/dotless-de/vagrant-vbguest/issues/351

**Comment by niro08** [comment]
Hi guys, I get a similar error - 
`Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7,086 kB]
Fetched 14.7 MB in 4s (3,172 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-headers-4.9.0-9-amd64
E: Couldn't find any package by glob 'linux-headers-4.9.0-9-amd64'
E: Couldn't find any package by regex 'linux-headers-4.9.0-9-amd64'
==> mag2.loc: Checking for guest additions in VM...
    mag2.loc: No guest additions were detected on the base box for this VM! Guest
    mag2.loc: additions are required for forwarded ports, shared folders, host only
    mag2.loc: networking, and more. If SSH fails on this machine, please install
    mag2.loc: the guest additions and repackage the box to continue.
    mag2.loc:
    mag2.loc: This is not an error message; everything may continue to work properly,
    mag2.loc: in which case you may ignore this message.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y linux-headers-`uname -r` dkms

Stdout from the command:

Reading package lists...
Building dependency tree...
Reading state information...


Stderr from the command:

E: Unable to locate package linux-headers-4.9.0-9-amd64
E: Couldn't find any package by glob 'linux-headers-4.9.0-9-amd64'
E: Couldn't find any package by regex 'linux-headers-4.9.0-9-amd64'
`

**Comment by zepgram** [comment]
Can you try with this box: geerlingguy/debian9 ? The latest guest additions are already installed.
If it's not working I'll migrate the current vagrant from Debian to Ubuntu and this will definitely solve the current issue.

**Comment by niro08** [comment]
@zepgram, Thanks for the quick response. 
I added geerlingguy/debian9 vm box and executed command:
`vagrant destroy`

After that `vagrant up` command was executed without errors and magento 2 on virtual machine was successfully installed.
Thank You very much!
