### ISSUE TITLE
Cron causing high CPU (when cache disabled)

### ISSUE THREAD

**Issue by srgrbkl** [zepgram/magento2-fast-vm#35]
![unnamed](https://user-images.githubusercontent.com/17824457/66986174-05ebac00-f0c7-11e9-906d-75381d050620.png)

**Comment by zepgram** [comment]
It would be the same on other scopes like admin or frontend. Magento cannot run properly with all cache disabled.
This result in timeout must of the time.
A simple use case: disable all cache and run only bin/magento to print out commands, it takes ~30 seconds to process.

**Comment by srgrbkl** [comment]
I tried to upgrade m2 but got 502 at some step (the cache disable when upgrade and CPU-100%)

**Comment by zepgram** [comment]
Cache is supposed to be flushed but not disabled during upgrade.
Try to run bin/magento cache:enable before your operations.

**Comment by srgrbkl** [comment]
i upgrated from the Magento Admin (Web Setup Wizard) - in this case, the cache is disable

**Comment by zepgram** [comment]
I have no solution to improve the wizard. You could try to update from composer.json it's the best practice to upgrade magento.
