### ISSUE TITLE
process stuck during installation

### ISSUE THREAD

**Issue by DWDRemco** [zepgram/magento2-fast-vm#4]
![image](https://user-images.githubusercontent.com/44568181/47843500-17f21300-ddc0-11e8-8096-63061fe5c4df.png)
My process stuck during installation. I already tried different configurations( uncomment # v.gui=true, different config files). With and without mage2.
I also create new ssh without pass, but still crashing. If I install just system it will install the box, but i cant install magento2 on the box. I am running vagrant 2.2.0 and VB 5.2.2 on windows 10 pro.

**Comment by zepgram** [comment]
Hi, 

There is maybe an issue with prestissimo, which is supposed to speed up composer installation (installed in provision/010-system-packages.sh)

To setup your installation without prestissimo and saving your time by not destroying vagrant:
1. Connect with SSH, run "composer global remove hirak/prestissimo".
2. Exit the box, then modify the config.yaml to run only Magento installation.
3. Run vagrant provision

Or by destroying vagrant:
1. Comment line 53 in system-packages.sh
2. Run vagrant destroy
3. Run vagrant up

If it doesn't fix it. You could use composer install with verbose option to get more info.
