### ISSUE TITLE
How easy to clone using this package?

### ISSUE THREAD

**Issue by pmsteil** [zepgram/magento2-fast-vm#47]
Hello, I am looking for a dev setup where it will be very easy to clone an existing working dev magento2 install and database and get the 2nd one up and running very quickly, like in 5 minutes.  Is that possible with this package?

What is the process to do that?

Thanks!

**Comment by zepgram** [comment]
Dual project are not automatically supported, it would requires some change to have a one shot full process.

Theorically it could be done in 2 steps : first by provisioning the primary project (vagrant up), and re-run the "magento" provisionner with modified values for the secondary project in config.yaml but, it would requires manual change by the developer and the "project" variable should also be modifiable through config.yaml (db and directory are commonly named "magento")
