### ISSUE TITLE
Magento composer installer problem: Could not delete

### ISSUE THREAD

**Issue by Vikwip** [zepgram/magento2-fast-vm#48]
Hello,

I'm currently stuck during the Magento installation process because of the magento-composer-installer plugin. I also did a system installation and then used the following command from the magento [devdocs](https://devdocs.magento.com/cloud/before/before-setup-env-2_clone.html), but I always get the same error:

```shell
composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
    Finished: success: 0, skipped: 0, failure: 334, total: 334
Package operations: 460 installs, 0 updates, 0 removals
  - Installing magento/magento-composer-installer (0.1.13): Loading from cache
Plugin installation failed, rolling back
  - Removing magento/magento-composer-installer (0.1.13)

  [RuntimeException]
  Could not delete /home/vagrant/magento/magento2/vendor/magento/magento-composer-installer/src/MagentoHackathon:
```
I'm using Windows 10 as host machine.

Composer 1.9.2
PHP 7.2
Vagrant 2.2.6
Virtual Box 6.0.16

Do you have any idea how to resolve that error?

Thanks

**Comment by zepgram** [comment]
Yes it's an issue with NFS. You must fallback to "default" for mount option.

**Comment by Vikwip** [comment]
Thanks for your response. However mount was actually already set to "default" before launching vagrant.

Otherwise Ive had another error during the pre-installation process:

`PS C:\windows\system32> Add-MpPreference -ExclusionProcess winnfsd.exe`

`Add-MpPreference : Fehler beim Vorgang: 0x800106ba. Vorgang: MpPreference. Ziel: ConfigListExtension.`
`In Zeile:1 Zeichen:1`
`+ Add-MpPreference -ExclusionProcess winnfsd.exe`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
  ` + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) `  `[Add-MpPreference], CimException`
    `+ FullyQualifiedErrorId : HRESULT 0x800106ba,Add-MpPreference`

`Add-MpPreference : Fehler beim Vorgang: 0x%1!x!`
`In Zeile:1 Zeichen:1`
`+ Add-MpPreference -ExclusionProcess winnfsd.exe`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
   ` + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) ` `[Add-MpPreference], CimException`
    `+ FullyQualifiedErrorId : HRESULT 0x800106ba,Add-MpPreference`

Would there be a connection with my current issue?

**Comment by zepgram** [comment]
Yep, try to follow the beginning of this tutorial :
https://onilab.com/blog/install-magento-2-on-localhost-a-windows-10-guide/
It should solve your issue to turn on virtualization.

**Comment by Vikwip** [comment]
Mmmm...Okay thanks for the link, but virtualization was actually already turned on in my BIOS settings.

**Comment by zepgram** [comment]
Oups, ok then you should try rsync just for install. And then fallback to
default after your composer installation.

**Comment by Vikwip** [comment]
Hi zepgram,

Thanks, it worked this time! I put rsync instead of default in the mount setting and I didn't get the error.
Do I have to use rsync just for composer installation?

**Comment by zepgram** [comment]
Yep on windows10 sometimes there is an issue with mounted files and specially with composer install. Once it's done and rsync back has been correctly completed you can fallback to default mount, it should work correctly.

**Comment by Vikwip** [comment]
Okay thank you again for your explanations. Let me ask you one more question :) Should I install [WinNFSd ](http://winnfsd.sourceforge.net/) software on my computer, in order to avoid the winnfsd.exe error?

**Comment by zepgram** [comment]
If OS is correctly detected, the plugin "winnfsd" is supposed to be installed:
https://github.com/zepgram/magento2-fast-vm/blob/master/Vagrantfile#L26
Could you run `vagrant plugin install vagrant-winnfsd` and tell me the result ?
If it's already installed then you should try to install the software directly.

**Comment by Vikwip** [comment]
I guess that the plugin wasn't yet installed on my machine:

`> cd .\magento2-fast-vm\`
`> vagrant plugin install vagrant-winnfsd`
`Installing the 'vagrant-winnfsd' plugin. This can take a few minutes...
Installed the plugin 'vagrant-winnfsd (1.4.0)'!`

**Comment by zepgram** [comment]
It should work now :)

**Comment by Vikwip** [comment]
Hi,
Mmmm....I still got the same error while running the Add-MpPreference command.

**Comment by zepgram** [comment]
Well the error code "0x800106ba" indicates an issue with windows defender.
According to Google, this error is prompted when windows defender could not
be started.

Do you have windows defender turned on ?

**Comment by Vikwip** [comment]
Yes, windows defender is turned on and seems to nomally work.

**Comment by Vikwip** [comment]
I also work on my work computer, (I've admin access on it). Maybe some settings are still restricted on it.

**Comment by Vikwip** [comment]
Hello zepgram,
Is this command `Add-MpPreference -ExclusionProcess winnfsd.exe` really necessary anyway? I don't think it's really blocking to continue the installation.

**Comment by zepgram** [comment]
Hi Vikwip, it's necessary if you have NFS mount issues with Windows, otherwise you can skip it.

**Comment by Vikwip** [comment]
Hi zepgram, 
Okay, thanks for your explanations again. I use for the moment rsync to mount my machine, in order to avoid problems with composer.
I can close the issue.
