### ISSUE TITLE
How to configure nginx to use multiple stores with the same domain

### ISSUE THREAD

**Issue by srgrbkl** [zepgram/magento2-fast-vm#57]
need to create multiple stores with the same domain:
site.com/en/
site.com/fr/
site.com/de/
I changed magento.ngnix.conf (added  fastcgi_param  MAGE_RUN_CODE 'en'; fastcgi_param  MAGE_RUN_TYPE store;), but I get a 404 error().
do you have any ideas?

**Comment by zepgram** [comment]
Hi @srgrbkl  
Did you change the base_url foreach website ?

**Comment by srgrbkl** [comment]
yes, base_url now 
http://dev.site.com/en/

**Comment by zepgram** [comment]
I'm note sure this is a best practice, but this should work: 
https://gist.github.com/thagxt/0f605f0a8a95c79302db0d2f04383788
