### ISSUE TITLE
Vagrant up network DHCP problem

### ISSUE THREAD

**Issue by Vikwip** [zepgram/magento2-fast-vm#58]
Hello zepgram, 
I've had today a forced virtual box update to 6.1.4 version (I had previously the 6.0.18) and now I have an error on vagrant up and get stuck:

	==> zepgram: Clearing any previously set network interfaces...
	vagrant : A host only network interface you're attempting to configure via DHCP
	In Zeile:1 Zeichen:1
	+ vagrant up
	+ ~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (A host only net...figure via DHCP:String) [], RemoteException
		+ FullyQualifiedErrorId : NativeCommandError
	 
	already has a conflicting host only adapter with DHCP enabled. The
	DHCP on this adapter is incompatible with the DHCP settings. Two
	host only network interfaces are not allowed to overlap, and each
	host only network interface can have only one DHCP server. Please
	reconfigure your host only network or remove the virtual machine
	using the other host only network.

Did you already have something similar, could you help me to resolve this? Thanks

**Comment by zepgram** [comment]
It should be resolve with #59

**Comment by Vikwip** [comment]
Okay, but I'm not sure what I'm supposed to do here. Should I destroy my machine and create a new one or update it?

**Comment by zepgram** [comment]
Nop, juste pull master and vagrant up. This should work.

**Comment by Vikwip** [comment]
Okay thanks it's working now!
