### ISSUE TITLE
Win 10 vagrant up failing at magento installation 

### ISSUE THREAD

**Issue by Jimmyballantyne** [zepgram/magento2-fast-vm#61]
zepgram: --- Magento installation sequence ---
    zepgram: sudo
    zepgram: :
    zepgram: composer: command not found
    zepgram: sudo
    zepgram: :
    zepgram: composer: command not found
    zepgram: sudo
    zepgram: :
    zepgram: composer: command not found
    zepgram: chmod:
    zepgram: cannot access '/home/vagrant/magento/bin/magento'
    zepgram: : No such file or directory
    zepgram: sudo
    zepgram: :
    zepgram: /home/vagrant/magento/bin/magento: command not found
    zepgram: sudo
    zepgram: :
    zepgram: /home/vagrant/magento/bin/magento: command not found
The SSH command responded with a non-zero exit status.

Am I missing something to install composer?

**Comment by zepgram** [comment]
Hi, something failed before because composer is installed at very start here : https://github.com/zepgram/magento2-fast-vm/blob/master/provision/010-system-packages.sh

**Comment by Jimmyballantyne** [comment]
Hi,

My bad, the earliest error I can see is elastic search fails to install, this then seems to block php, composer etc being installed:

     dev.magento.com: Get:33 https://packages.sury.org/php stretch/main amd64 php7.3-soap amd64 7.3.18-1+0~20200515.59+debian9~1.gbp12fa4f [110 kB]
    dev.magento.com: Get:34 https://packages.sury.org/php stretch/main amd64 php7.3-sqlite3 amd64 7.3.18-1+0~20200515.59+debian9~1.gbp12fa4f [24.3 kB]
    dev.magento.com: Get:35 https://packages.sury.org/php stretch/main amd64 php7.3-xml amd64 7.3.18-1+0~20200515.59+debian9~1.gbp12fa4f [103 kB]
    dev.magento.com: Get:36 https://packages.sury.org/php stretch/main amd64 php7.3-zip amd64 7.3.18-1+0~20200515.59+debian9~1.gbp12fa4f [20.2 kB]
    dev.magento.com: Err:9 https://artifacts.elastic.co/packages/6.x/apt stable/main amd64 elasticsearch all 6.8.10
    dev.magento.com:   Hash Sum mismatch
    dev.magento.com:   Hashes of expected file:
    dev.magento.com:    - SHA512:d47aa0dfc4726f98bd0664f914eb8d7f4d59bf637e6264cfc7e6301c116e11fd7bf3f7b9b71eaadff6f4cc6f691af7c66023a85c1fc9d07e5ee0e5a65b698e60
    dev.magento.com:    - SHA256:bf2da5704cf73d164b1d593ada1df634c8cdd747f3b769197d9b2c6fd78ad0f5
    dev.magento.com:    - SHA1:7220510c6f578baf14750052694ee1459ef817cb [weak]
    dev.magento.com:    - MD5Sum:c5bc763990cbc63d1490593558462e24 [weak]
    dev.magento.com:    - Filesize:149509708 [weak]
    dev.magento.com:   Hashes of received file:
    dev.magento.com:    - SHA512:b57e94ab49f255ea5141dc4639d3ed339f0e912be963dd70d96715d91dce5ef17b1986aa30a46c804ed27ca30f93757c2d3a8b71db3333b60323d96d648650cf
    dev.magento.com:    - SHA256:84641ad056b41f633576c4315c625cea1167a145a0308a0a121daa11429c92c1
    dev.magento.com:    - SHA1:b6d11dec281c8229626d049f0a2e356cd3de332d [weak]
    dev.magento.com:    - MD5Sum:40e22d5ce4093453b46af753f67f256e [weak]
    dev.magento.com:    - Filesize:149509708 [weak]
    dev.magento.com:   Last modification reported: Wed, 03 Jun 2020 12:39:48 +0000
    dev.magento.com: Fetched 195 MB in 12s (15.7 MB/s)
    dev.magento.com: E
    dev.magento.com: :
    dev.magento.com: Failed to fetch https://artifacts.elastic.co/packages/6.x/apt/pool/main/e/elasticsearch/elasticsearch-6.8.10.deb  Hash Sum mismatch
    dev.magento.com:    Hashes of expected file:
    dev.magento.com:     - SHA512:d47aa0dfc4726f98bd0664f914eb8d7f4d59bf637e6264cfc7e6301c116e11fd7bf3f7b9b71eaadff6f4cc6f691af7c66023a85c1fc9d07e5ee0e5a65b698e60
    dev.magento.com:     - SHA256:bf2da5704cf73d164b1d593ada1df634c8cdd747f3b769197d9b2c6fd78ad0f5
    dev.magento.com:     - SHA1:7220510c6f578baf14750052694ee1459ef817cb [weak]
    dev.magento.com:     - MD5Sum:c5bc763990cbc63d1490593558462e24 [weak]
    dev.magento.com:     - Filesize:149509708 [weak]
    dev.magento.com:    Hashes of received file:
    dev.magento.com:     - SHA512:b57e94ab49f255ea5141dc4639d3ed339f0e912be963dd70d96715d91dce5ef17b1986aa30a46c804ed27ca30f93757c2d3a8b71db3333b60323d96d648650cf
    dev.magento.com:     - SHA256:84641ad056b41f633576c4315c625cea1167a145a0308a0a121daa11429c92c1
    dev.magento.com:     - SHA1:b6d11dec281c8229626d049f0a2e356cd3de332d [weak]
    dev.magento.com:     - MD5Sum:40e22d5ce4093453b46af753f67f256e [weak]
    dev.magento.com:     - Filesize:149509708 [weak]
    dev.magento.com:    Last modification reported: Wed, 03 Jun 2020 12:39:48 +0000
    dev.magento.com: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    dev.magento.com: composer
    dev.magento.com: /tmp/vagrant-shell: line 88: php: command not found
    dev.magento.com: c
    dev.magento.com: u
    dev.magento.com: r
    dev.magento.com: l
    dev.magento.com: :
    dev.magento.com:
    dev.magento.com: (
    dev.magento.com: 23) Failed writing body (0 != 16110)
    dev.magento.com: sudo
    dev.magento.com: :
    dev.magento.com: composer: command not found
    dev.magento.com: --2020-06-04 13:36:28--  https://www.thawte.com/roots/thawte_Premium_Server_CA.pem
    dev.magento.com: Resolving www.thawte.com (www.thawte.com)...
    dev.magento.com: 45.60.198.209
    dev.magento.com: Connecting to www.thawte.com (www.thawte.com)|45.60.198.209|:443...
    dev.magento.com: connected.


I've tried adding apt-get update to the beginning of the file but it just gives a decryption error instead?

**Comment by Jimmyballantyne** [comment]
Thank for coming back so quickly btw!

**Comment by Jimmyballantyne** [comment]
Ok I commented out the elastic search install and it works up to the point of magento install where it fails:

 Installing magento/project-community-edition (2.3.4):
    dev.magento.com: Downloading
    dev.magento.com:  (100%)
    dev.magento.com:
    dev.magento.com:   [RuntimeException]
    dev.magento.com:   Could not delete /home/vagrant/magento/:

**Comment by zepgram** [comment]
Did you destroy the vagrant before running the install ?

**Comment by zepgram** [comment]
Everything is working here. Make sure you don't open the project before it's installed (with any IDE or even with windows explorer) because you can have a conflict on file permissions (windows user / vagrant). 
1. Remove the directory www/magento in vagrant directory before reinstalling.
1. Do not open it until installation finished.

**Comment by Jimmyballantyne** [comment]
Hi, No matter what I try it won't work. I destroy and remove the box each time,  I delete the directory but still the same issue. One time it went to the magento installation which exited with a failed checksum, then with a segmentation fault. The rest of the time it just gives the

**Comment by Jimmyballantyne** [comment]
[RuntimeException]
    dev.magento.com:   Could not delete /home/vagrant/magento/:

Thanks for your help but I'll have to try another way to set up a dev machine

**Comment by nabeelaejaz** [comment]
I am having same issue here. What to do?
