### ISSUE TITLE
No access to admin page : https://dev.xxxxx.com/admin get 404 error code

### ISSUE THREAD

**Issue by wash34000** [zepgram/magento2-fast-vm#63]
Hello,

I've try twice to setup the VM. All setup is good. Magento front is working but i cannot get backend page. each time i get 404 error page.

I've tried to change "admin" backend frontname without success with :
php bin/magento setup:config:set --backend-frontname="DSFgSsS45"

I try this too without success : 
php -f bin/magento cache:flush
sudo rm -rf var/cache var/generation var/page_cache
php -f bin/magento cache:disable
chmod -R 777 var
chmod -R 777 pub
chmod -R 777 generated

When i try to change with chmod the folder autorization doesn't change : 
BEFORE : drwxrwxr--  13 vagrant www-data    416 Jul 21 12:17 pub
AFTER : drwxrwxr--  13 vagrant www-data    416 Jul 21 12:17 pub

PS : I'm using this settings :
magento:
  url: 'dev.xxxxx.com'
  source: 'composer'
  edition: 'community'
  version: '2.3.5'
  php_version: 'default'
  sample: 'true'
  mode: 'developer'
  currency: 'EUR'
  language: 'en_US'
  time_zone: 'Europe/Paris'
  crypt_key: ''

Thanks

**Comment by wash34000** [comment]
I've tried the same config with rsync instead of nfs and the admin page is working with no more 404 error page.
I think this is error come with file permission of nfs settings but i don't know how to check that.

**Comment by zepgram** [comment]
Do you have 'admin' => 'DSFgSsS45' in your app/etc/env.php ?
You can check nginx log to get more info.

I'll try on my side with NFS.

**Comment by wash34000** [comment]
yes i have it on app/etc/env.php.

/var/log/nginx/magento.access.log
/var/log/nginx/magento.error.log
stay empty all times so i cannot debug the admin errors ...

**Comment by wash34000** [comment]
Another details : 
when i run permission with mount set as nfs it take 0 second to run without any console return information.
when i run permission with mount set as rsync it take long time (normal time to reset all permission) and return "Applying permissions to /home/vagrant/magento".

If this could help you !

**Comment by zepgram** [comment]
Yep, it's because I made a check to skip permissions on NFS because they are not editable: https://github.com/zepgram/magento2-fast-vm/blob/master/provision/100-magento-pre.sh#L47

**Comment by wash34000** [comment]
I understand that they are not editable but are they correct for all folder ? 
With NFS i have no admin page / wrong cache folder image link / no log writted.

How can i help you ?

**Comment by zepgram** [comment]
Could you check the value in db of: 
SELECT * FROM core_config_data WHERE path = 'web/seo/use_rewrites'

Set the value to 0, you can also disable it from back-office.
Once it's done you should be able to access it this way: dev.xxxxxxxxx.com/index.php/admin

Not ideal, but this should work I guess.

**Comment by wash34000** [comment]
I already try this without success. Like i cannot check logs i cannot debug it ...

**Comment by zepgram** [comment]
I reinstalled the project and I'm able to login in back-office :
![image](https://user-images.githubusercontent.com/16258478/88458082-a14a5280-ce8b-11ea-82e4-4761730946a5.png)

Did you try in private navigation ? Sometimes navigator cookie force the redirection.

Is your /etc/hosts looking similar to this ? 
# magento fast-vm
192.168.200.50   dev.magento.com
