### ISSUE TITLE
Error in install script

### ISSUE THREAD

**Issue by wash34000** [zepgram/magento2-fast-vm#64]
While is vagrant up i have this warning : 

dev.xxxxxx.com: chown: changing ownership of '/home/vagrant/magento/vendor/magento/magento2-base/dev/tests/api-functional/_files/Magento/TestModuleJoinDirectives/etc/acl.xml': Operation not permitted

**Comment by zepgram** [comment]
Hi, did you made change on permissions from your host machine ?

If you use 'nfs' for mount option, permissions cannot be change and are setted for the whole directory at this line: 
https://github.com/zepgram/magento2-fast-vm/blob/master/Vagrantfile#L69

Try to remove all files, and re-install to avoid this issue.

**Comment by wash34000** [comment]
You're right it's working
