### ISSUE TITLE
Rsync setup error

### ISSUE THREAD

**Issue by wash34000** [zepgram/magento2-fast-vm#65]
I've run vagrant up with rsync in setting and i get this error :

 dev2.xxxxxxxx.com: vagrant rsync-back dev2.xxxxxxxx.com | vagrant rsync-auto --rsync-chown dev2.xxxxxxxx.com
    dev2.xxxxxxxx.com: An invalid option was specified. The help for this command
    dev2.xxxxxxxx.com: is available below.
    dev2.xxxxxxxx.com: 
    dev2.xxxxxxxx.com: Usage: vagrant rsync-back [vm-name]

I've modded dependency.rb to try to use VM machine name but i get the same error. 

Is it possible that a space in machine name could make this error ?

Kind regards

**Comment by zepgram** [comment]
This part of the script from dependency.rb is a simple utility to send back files from guest machine to your host machine (rsync doesn't work like NFS and requires this kind of tricks)

So if you have any issue, you can juste remove this command line from the script and try to run it manually from your shell.

The value expected is the machine name corresponding to 'host_name' in config.yaml.
If you take config.yaml.example the default machine name is "zepgram".

**Comment by wash34000** [comment]
You're right i make a mistake with config.yaml and set the **same name** for **url** and **hostname** : 
host_name: 'dev2.xxxxxxxx.com'
url: 'dev2.xxxxxxxx.com'

i change it to :
host_name: '**dev2**'
url: '**dev2**.xxxxxxxx.com'

and **it's work** !
