### ISSUE TITLE
Install error magento 2.4.0 on windows 10

### ISSUE THREAD

**Issue by ICT-DHS** [zepgram/magento2-fast-vm#70]
I get an error installing with the new version (1.3.5) for Magento 2.4.0 on windows 10. 
![error-zepgram-240](https://user-images.githubusercontent.com/70269551/91302716-32705a00-e7a7-11ea-8229-44aff058fb76.PNG)

**Comment by zepgram** [comment]
I didn't find how to resolve this. But I know it happens sometimes on first installation for windows computer with "nfs" option.

If you want to avoid this, you can set mount option to "rsync" or "default".
