### ISSUE TITLE
Clean install magento 2.4 and nginx will fail nginx

### ISSUE THREAD

**Issue by dutchwebdesign** [zepgram/magento2-fast-vm#77]
After clean install with this latest box I got the following error:

```
-- Unit nginx.service has begun starting up.
Oct 26 11:11:45 zepgram nginx[24775]: nginx: [emerg] open() "/home/vagrant/extra/magento.nginx.conf" failed (2: No such file or directory) in /etc/nginx/sites-enab
Oct 26 11:11:45 zepgram nginx[24775]: nginx: configuration file /etc/nginx/nginx.conf test failed
```
This file is present in the host project with .
![image](https://user-images.githubusercontent.com/40382854/97166435-8ab2e080-1785-11eb-9a37-1cf24b621d93.png)

host is ubuntu 16

config file:

vmconf:
  machine_name: 'Vagrant Magento 2'
  network_ip: '192.168.200.50'
  host_name: 'zepgram'
  memory: '4096'
  cpus: '2'
  mount: 'nfs'
  path: 'root'
  provision: 'all'
composer:
  username: '-'
  password: '-'
git:
  name: '-'
  email: '-'
  host: '-'
  repository: '-'
magento:
  url: '-'
  source: 'development'
  edition: 'community'
  version: '2.4.0'
  php_version: 'default'
  sample: 'false'
  mode: 'development'
  currency: 'EUR'
  language: 'nl_NL'
  time_zone: 'Europe/Amsterdam'
  crypt_key: '-'

**Comment by zepgram** [comment]
Hi, it's because the native sample file for nginx configuration is missing.
Just add your own, or simply copy paste this one in your root project: https://github.com/magento/magento2/blob/2.4-develop/nginx.conf.sample

**Comment by zepgram** [comment]
Did the provisionner "120-magento-post.sh" run correctly ? 
You should have a nginx.conf in your root project (copied on line 34): https://github.com/zepgram/magento2-fast-vm/blob/master/provision/120-magento-post.sh#L34 
Then the file is copied to extra directory on line 37: https://github.com/zepgram/magento2-fast-vm/blob/master/provision/120-magento-post.sh#L37

**Comment by dutchwebdesign** [comment]
thx for the quick reply. No I only have nginx.conf.sample in root dir maybe something here [https://github.com/zepgram/magento2-fast-vm/blob/master/provision/120-magento-post.sh#L33] failed. I dont have logs of the installation left open. Is there a way to see them back? (I fixed it now by manually placing the home/vagrant/extra/magento.nginx.conf)

**Comment by zepgram** [comment]
It should be there (according to this: https://stackoverflow.com/questions/26385415/where-does-vagrant-store-logs):
~/VirtualBox VMs/vagrant_box_name/Logs

**Comment by dutchwebdesign** [comment]
Thanks unfortunate it does not contain the installation logs. If this does not happen at anyone else you can close :)
