### ISSUE TITLE
Elasticsearch issue on first install under Windows

### ISSUE THREAD

**Issue by deepaw-** [zepgram/magento2-fast-vm#78]
Hello,

I got an error for Elasticsearch when I try to install Magento 2 in the virtual machine it was something like this:
`Could not validate a connection to Elasticsearch. No alive nodes found in y
    zepgram:   our cluster
`
I was able to fix by adding this parameter `--elasticsearch-host='127.0.0.1'` to the setup:install command in `provision/110-magento-app.sh` 

Thank you!

**Comment by zepgram** [comment]
This should be resolved on #80
