### ISSUE TITLE
Install error magento 2.4.0 on osx 10.15.7 (catalina)

### ISSUE THREAD

**Issue by FabienGregoire** [zepgram/magento2-fast-vm#82]
I get an error installing for Magento 2.4.2 on MacOS 10.15.7 (Catalina). 
I used the master branch.

I tried to change the hostDirectory in the VagrantFile but it failed. The script tried again to mount the same host directory (/home/vagrant/magento). Maybe there are others locations to change this hostDirectory variable ? Or the solution is elsewhere ?

![image](https://user-images.githubusercontent.com/17239152/112812246-2de18c00-907d-11eb-89a7-913611781949.png)

**Comment by zepgram** [comment]
Hi,

You should not change the variable "hostDirectory", the path must be in project root ./www

This error can be printed for 2 reasons : 
- The directory doesn't exist
- The directory is currently opened in an other program

**Comment by FabienGregoire** [comment]
Hi Zepgram,

Thank you for your return. Concerning the hostDirectory, I only use the absolute path because some comments in forum speak about this issue in Catalina. So I use this directory well.

I checked if the directory exists and it's ok. How can I know if it is currently opened in an other program ?

Other information, just in case the problem comes from elsewhere.
In the vagrant machine (so after a 'vagrant ssh'), when I list the contents of the /home/vagrant/magento directory with the 'ls' command, I had this error :
`ls: cannot open directory '.': Stale file handle`

The result of 'ls -l' on the parent directory is :
`drwxr-xr-x 3     501 dialout   96 Mar 28 15:56 magento`

Thanks again for your help

**Comment by zepgram** [comment]
Could you give me the value you gave to `hostDirectory` ?

**Comment by FabienGregoire** [comment]
My hostDirectory is `"/System/Volumes/Data/Users/MY_USER_ACCOUNT/Documents/Projets/magento2-fast-vm/www/#{projectName}"`
But maybe it's not necessary because it was a bug on an old vagrant version. 
I found the real solution ! 
The issue comes from the nfsd permissions. I gave the full access disk to /sbin/nfsd, then vagrant destroy & vagrant up.

I have no more issue about it :).

Thanks for your time !
