### ISSUE TITLE
problem with permissions (after deploy project from repository)

### ISSUE THREAD

**Issue by srgrbkl** [zepgram/magento2-fast-vm#86]
after deploy project from repository i got an error(  mount: 'rsync'):
_1 exception(s):
Exception #0 (Magento\Framework\Exception\FileSystemException): The path "/home/vagrant/magento/pub/static/." is not writable._

adding this code to vagrantfile solves problem:
  # Bindfs options
  config.bindfs.default_options = {
    **force_user:   'vagrant',**
    force_group:  'www-data',
    **perms:        'u=rwx:g=rwx:o=rx'**
  }

**Comment by zepgram** [comment]
HI @srgrbkl puting back this code will probably throw an error when you we'll try to add an image, this is related to : https://github.com/zepgram/magento2-fast-vm/issues/79

Do you think permission were correctly applied ?
Did this error thrown when you tried to access magento ? Did you try to run the `permission` command ?

**Comment by srgrbkl** [comment]
I did not study README.md after update, run permission - works good. Thanks @zepgram!
