### ISSUE TITLE
Fails on setup with composer

### ISSUE THREAD

**Issue by alexjamesbrown** [zepgram/magento2-fast-vm#94]
I see a lot of these warnings:

zepgram: Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/

But ultimately this is the error:

    zepgram: Writing lock file
    zepgram: Generating autoload files
    zepgram: 20 packages you are using are looking for funding.
    zepgram: Use the `composer fund` command to find out more!
   zepgram: Use the `composer fund` command to find out more!
    zepgram:   - Installing magento/module-bundle-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-theme-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-cms-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-customer-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-downloadable-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-grouped-product-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-msrp-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-offline-shipping-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-product-links-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-review-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-catalog-rule-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-sales-rule-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-configurable-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-sales-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-swatches-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-tax-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-widget-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/module-wishlist-sample-data (100.4.0): Downloading (100%)
    zepgram:   - Installing magento/sample-data-media (100.4.0): Downloading (100%)
    zepgram:
    zepgram: Installation failed, reverting ./composer.json to its original content.
    zepgram:
    zepgram: In FilesystemRepository.php line 63:
    zepgram:
    zepgram:   Invalid repository data in /home/vagrant/magento/vendor/composer/installed.
    zepgram:   json, packages could not be loaded: [Seld\JsonLint\ParsingException] "/home
    zepgram:   /vagrant/magento/vendor/composer/installed.json" does not contain valid JSO
    zepgram:   N
    zepgram:   Parse error on line 1:
    zepgram: There is an error during sample data deployment. Composer file will be reverted.
    zepgram:
    zepgram:   ^
    zepgram:   Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
    zepgram:
    zepgram:
    zepgram: require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--skip-magento-root-plugin] [--use-default-magento-values] [--interactive-magento-conflicts] [--base-magento-edition BASE-MAGENTO-EDITION] [--base-magento-version BASE-MAGENTO-VERSION] [--] [<packages>...]
    zepgram:
    zepgram: Can't run this operation: deployment configuration is absent. Run 'magento setup:config:set --help' for options.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

It seems to be consistent - have retried a few times, same error

**Comment by alexjamesbrown** [comment]
hi @zepgram -

Hadn't changed much from the default:

vmconf:
  machine_name: 'Vagrant Magento 2'
  network_ip: '192.168.200.50'
  host_name: 'zepgram'
  memory: '8192'
  cpus: '1'
  mount: 'nfs'
  path: 'root'
  provision: 'all'
composer:
  username: 'x'
  password: 'x'
git:
  name: 'John Doe'
  email: 'john@doe.com'
  host: 'github.com'
  repository: 'ssh://git@github.com:project-name.git'
magento:
  url: 'dev.magento.com'
  source: 'composer'
  edition: 'community'
  version: '2.4.3'
  php_version: 'default'
  sample: 'true'
  mode: 'developer'
  currency: 'GBOP'
  language: 'en_GB'
  time_zone: 'Europe/London'
  crypt_key: 'thiswouldbealongkey'

**Comment by zepgram** [comment]
Well that's a known issue. I've never been able to fix this because I don't understand why files seems not available on mount.

same issue is related here: https://github.com/zepgram/magento2-fast-vm/issues/70

Execute vagrant destroy, and set the mount to rsync, this may solve this error.
