### ISSUE TITLE
Error with certificates that makes the VM not able to install PHP

### ISSUE THREAD

**Issue by Vbak** [zepgram/magento2-fast-vm#98]
When I m trying to use that VM I m getting :

E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

That makes PHP installation fail and then I have to install it manually when I log in to it.
Is there a fix for that? None seems to have worked for me after googling it.

Thanks

**Comment by zepgram** [comment]
Hello @Vbak I just did it with default config.yml and this is working for me: 
![image](https://user-images.githubusercontent.com/16258478/163167870-f1114a05-c42f-4434-9317-986d95b76cdd.png)

Which version of Magento are you trying to install ?

**Comment by Vbak** [comment]
Magento 2.4.3. I m on linux mint.
Vagrant 2.2.19
VirtualBox Graphical User Interface Version 5.2.42_Ubuntu r137960
If that makes any difference. 
thanks

**Comment by zepgram** [comment]
Well even with magento 2.4.3 the installation work: 
![image](https://user-images.githubusercontent.com/16258478/163180712-3b202537-59ef-4c5f-bd68-808125f0b26d.png)

Did you pull the latest master's version ?

**Comment by Vbak** [comment]
Hi,
Yes indeed. I guess you haven't come across with that error. 
I ll keep searching and update the question if I can get an answer. I thought this might known problem or something.
thanks
